[WIP] :lipstick: new homepage
lia-univali/cassie pull request #44
Opened 2021-03-04 00:17 UTC by AlissonSteffens

This PR introduces a new homepage for CASSIE

![screenshotfull](https://user-images.githubusercontent.com/6234230/109890265-c2ff8980-7c65-11eb-9216-bf3abd9d8476.jpg)

2021-03-16 18:09 UTC, vinigmartins commented on src/app/components/homepage/Footer.js
> +                CASSIE
I prefer without "cassie", but I understand the use for identity

2021-03-16 21:34 UTC, vinigmartins requested changes
The new home is marvelous, but needs some changes. 😄

2021-03-16 21:34 UTC, vinigmartins commented on src/i18n/en.js
> +                text: 'O projeto procura contribuir com ações e resultados para o bem e preservação do nosso planeta, tomando para si, a tarefa de cumprir os objetivos de desenvolvimento sustentável,
Change to:

The main objective of this project is to conduct a climate risk analysis (environmental and economic) and to determine possible adaptation measures, based on the future projection of environmental threats (e.g. storm waves), to increase the resilience of the port sector and adjacent areas in the Babitonga Bay, in an interdisciplinary-multiinstitutional network context.

2021-03-17 19:21 UTC, AlissonSteffens commented
@ViniciusAS pode validar novamente?

2021-03-18 16:09 UTC, vinigmartins requested changes
When I switch to English and go to FAQ or KNOWN ISSUES, the site switches back to Portuguese, and vice versa.

2021-03-18 16:09 UTC, vinigmartins commented on src/i18n/pt.js
> +                title: 'Analise de muitos dados',
typo corrections:

Análise de muitos dados

2021-03-18 16:18 UTC, vinigmartins requested changes

2021-03-18 16:18 UTC, vinigmartins commented on src/app/components/homepage/NavBar.js
> +          </Link>
The link is taking up almost the entire header.

![image](https://user-images.githubusercontent.com/30875400/111659157-c1989a00-87eb-11eb-8fbd-f606d4ce04dc.png)

2021-03-18 16:50 UTC, AlissonSteffens commented
Fixed almost everything. The problem with language changing though, I'll only solve after merging #45

2021-03-18 17:59 UTC, IsraelEfraim approved these changes
New homepage is very appreciable.

2021-03-18 18:39 UTC, vinigmartins approved these changes
Nice 💖

2021-03-18 18:52 UTC, merged